on:
  push:
    branches:
      '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test CMake Library Build Process
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the executable
        run: |
          cd executable
          mkdir build
          cd build
          cmake ..
          make
          ./test_executable

      - name: Run the executable
        run: |
          cd executable/build
          ./test_executable
